(function () {
  'use strict';
  var db=JSON.parse(document.getElementById('library-data').textContent), $=function(id){return document.getElementById(id);};
  var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
  var storage; try { storage=window.localStorage; } catch(e) { storage={getItem:function(){throw e;},setItem:function(){throw e;},removeItem:function(){throw e;}}; }
  var loaded=AGState.load(db,storage), state=loaded.workspace, blocked=loaded.blocked, restoring=false, pendingImport=null, compared=new Set();
  var resources={extension:{title:'Subject extension group',details:'Fictional availability: weekly 45-minute small group with a mathematics educator. Learner readiness and timetable fit require review. Cost unknown.'},mentor:{title:'Mentor-supported inquiry',details:'Fictional availability: fortnightly mentor meeting, project work between meetings. Mentor capacity, accessible materials, and supervision need confirmation. Cost unknown.'},access:{title:'Specialist access consultation',details:'Fictional availability: educator and learning-support specialist review task access together. Keep advanced challenge available while clarifying delivery and accommodations. Cost unknown.'}};
  function current(){return AGState.current(state);}
  function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
  function status(message,error){$('workflow-status').textContent=message;$('workflow-status').classList.toggle('error',!!error);}
  function persist(){ $('save-status').textContent=blocked ? loaded.message : AGState.save(state,storage); }
  function bindFields(){var c=current();AGState.fields.forEach(function(k){$('field-'+k).value=c.draft[k];});}
  function capture(){
    if(restoring)return;
    var context=window.AGWorkspace.rawContext();
    if(context.scenario!==state.activeCaseId){switchCase(context.scenario);return;}
    current().context=AGState.clone(context);current().selected=window.AGWorkspace.selected();persist();refresh();
  }
  function switchCase(id){
    if(!state.cases.some(function(c){return c.id===id;}))return;
    state.activeCaseId=id;restoring=true;window.AGWorkspace.setCase(current());restoring=false;bindFields();persist();refresh();status('Fictional case opened. Its draft and history are separate from other cases.');
    document.dispatchEvent(new CustomEvent('achievego:context-change'));
  }
  function download(data,name){var url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
  function entries(fields){return '<dl class="plan-summary">'+Object.keys(fields).map(function(k){return '<dt>'+esc(k.replace(/([A-Z])/g,' $1'))+'</dt><dd>'+esc(fields[k]||'Not recorded')+'</dd>';}).join('')+'</dl>';}
  function preview(){
    var c=current(),d=c.draft;
    $('plan-preview').innerHTML='<p><strong>'+esc(c.name)+'</strong> · fictional case</p>'+entries({goal:d.goal,baseline:d.baseline,opportunity:d.opportunity,support:d.support,responsible:d.responsible,delivery:d.delivery,ai:d.ai,accommodations:d.accommodations,reviewDate:d.reviewDate,adaptations:d.adaptations})+'<h3>Selected evidence</h3>'+(c.selected.length?'<ul>'+c.selected.map(function(id){var r=db.evidence_records.find(function(r){return r.id===id;});return '<li>'+esc(r.title)+' · '+esc(r.rating)+' · <a href="'+esc(db.sources[r.source_id].url)+'" target="_blank" rel="noopener">Source ↗</a></li>';}).join('')+'</ul>':'<p>No curated evidence selected. This draft remains a planning proposal; examine the evidence gap.</p>');
  }
  function history(){
    var c=current(),last=c.plans[c.plans.length-1];
    $('review-history').innerHTML=c.reviews.length?c.reviews.slice().reverse().map(function(r){return '<article class="history-entry"><p><strong>'+esc(r.date)+' · '+esc(r.decision)+'</strong></p><p>'+esc(r.rationale)+'</p><p class="small muted">'+(r.nextPlanId?'Linked to a subsequent plan version.':'Review of plan '+esc(c.plans.find(function(p){return p.id===r.planId;}).version)+'.')+'</p></article>';}).join(''):'<p class="empty">No review recorded yet. Confirm a demo plan and examine its response before recording a decision.</p>';
    $('version-history').innerHTML=c.plans.length?'<h3>Confirmed demo plans</h3>'+c.plans.slice().reverse().map(function(p){
      var prev=c.plans.find(function(x){return x.id===p.previousPlanId;}),changes=prev?AGState.fields.filter(function(k){return prev.fields[k]!==p.fields[k];}):[];
      var diffs=changes.map(function(k){return '<li><strong>'+esc(k)+'</strong>: '+esc(prev.fields[k]||'not recorded')+' → '+esc(p.fields[k]||'not recorded')+'</li>';});
      if(prev&&JSON.stringify(prev.evidenceIds)!==JSON.stringify(p.evidenceIds))diffs.push('<li>Evidence selections: '+esc(prev.evidenceIds.join(', ')||'none')+' → '+esc(p.evidenceIds.join(', ')||'none')+'</li>');
      if(prev&&JSON.stringify(prev.context)!==JSON.stringify(p.context))diffs.push('<li>Fictional learner context changed; inspect both exported snapshots.</li>');
      return '<details class="history-entry"><summary>Version '+p.version+' · '+esc(p.createdAt.slice(0,10))+' · Demo confirmed</summary>'+entries(p.fields)+(prev?'<h4>Changes from version '+prev.version+'</h4>'+(diffs.length?'<ul>'+diffs.join('')+'</ul>':'<p>No field changes.</p>'):'<p>Initial plan snapshot.</p>')+'</details>';
    }).join(''):'<p class="empty">No confirmed plan versions.</p>';
    var due=last?last.fields.reviewDate:'';
    $('case-summary').textContent=c.name.split(' · ')[0]+' · Grade '+c.context.grade+' · '+(c.draft.goal||'Learning goal to clarify')+(last?' · Plan '+last.version:' · Draft')+(due?' · Review '+due+(due<today()?' (due for review)':''):'');
  }
  function observations(){
    var c=current();
    $('observation-log').innerHTML=c.observations.length?c.observations.slice().reverse().map(function(o){return '<article class="history-entry"><p><strong>'+esc(o.date)+' · '+esc(o.measure)+'</strong></p><p>'+esc(o.value===null?'Missing observation':o.value)+' '+esc(o.unit)+' · AI: '+esc(o.ai)+'</p><p>Access accommodations: '+esc(o.accommodations||'Not recorded')+'</p><p>Delivery: '+esc(o.delivery||'Not recorded')+'</p><p>Learner: '+esc(o.feedback||'Not recorded')+'</p><p class="small muted">Synthetic observation · Plan '+esc(c.plans.find(function(p){return p.id===o.planId;}).version)+'</p></article>';}).join(''):'<p class="empty">No synthetic observations yet.</p>';
    if(!c.observations.length){$('assessment-view').innerHTML='<p class="empty">Add or load synthetic observations in Monitor. No learning trend can be inferred from an empty record.</p>';return;}
    var groups={};c.observations.forEach(function(o){var key=JSON.stringify([o.planId,o.measure,o.unit,o.ai,o.accommodations]);(groups[key]||(groups[key]=[])).push(o);});
    $('assessment-view').innerHTML=Object.keys(groups).map(function(k){
      var rows=groups[k].slice().sort(function(a,b){return a.date.localeCompare(b.date);}),first=rows[0],numeric=rows.filter(function(o){return o.value!==null;}),p=c.plans.find(function(p){return p.id===first.planId;});
      var values=numeric.map(function(o){return o.value;}),min=Math.min.apply(null,values),max=Math.max.apply(null,values);
      var bars=numeric.length>=2?'<div class="observation-bars" aria-hidden="true">'+numeric.map(function(o){var w=max===min?50:10+90*(o.value-min)/(max-min);return '<div><span>'+esc(o.date)+'</span><div class="bar-track"><div style="width:'+w+'%"></div></div><strong>'+esc(o.value)+'</strong></div>';}).join('')+'</div>':'';
      return '<article class="assessment-group"><h3>'+esc(first.measure)+' · '+esc(first.unit||'unit unspecified')+'</h3><p>Plan '+p.version+' · AI: '+esc(first.ai)+' · Accommodations: '+esc(first.accommodations||'not recorded')+'</p>'+bars+'<div class="table-scroll"><table><caption>Synthetic observations under these recorded conditions</caption><thead><tr><th scope="col">Date</th><th scope="col">Value</th><th scope="col">Delivery</th><th scope="col">Learner feedback</th></tr></thead><tbody>'+rows.map(function(o){return '<tr><td>'+esc(o.date)+'</td><td>'+esc(o.value===null?'Missing':o.value)+'</td><td>'+esc(o.delivery||'Not recorded')+'</td><td>'+esc(o.feedback||'Not recorded')+'</td></tr>';}).join('')+'</tbody></table></div><p class="small">'+(numeric.length>=2?'Descriptive change: '+esc(numeric[numeric.length-1].value-numeric[0].value)+' '+esc(first.unit)+'. This is not an intervention-effect estimate.':'Fewer than two numerical observations; no change calculated.')+'</p></article>';
    }).join('')+'<p class="notice">Different plans, measures, units, AI conditions, and accommodations are displayed separately. Matching labels alone do not establish that tasks or scoring were comparable.</p>';
  }
  function refresh(){
    preview();history();observations();
    var d=current().draft,r=resources[d.resource];$('resource-details').textContent=r?r.details:'Confirm availability, staffing, timetable, and access before committing resources.';
    var links=document.querySelectorAll('[data-stage-link]');links.forEach(function(link){var stage=link.dataset.stageLink,ready=stage==='understand'?!!d.readiness:stage==='plan'?!!d.goal:stage==='allocate'?!!current().plans.length:stage==='monitor'||stage==='assess'?!!current().observations.length:!!current().reviews.length;link.dataset.status=ready?'recorded':'draft';link.title=ready?'Information recorded; review its adequacy':'Draft / information still needed';});
    $('resume-demo').href='#workspace/'+(current().plans.length?'review':d.goal?'plan':'understand');
  }
  document.querySelectorAll('[data-field]').forEach(function(input){input.addEventListener('input',function(){current().draft[input.dataset.field]=input.value;persist();refresh();});input.addEventListener('change',function(){document.dispatchEvent(new CustomEvent('achievego:context-change'));});});
  document.addEventListener('achievego:context-change',capture);document.addEventListener('achievego:selection-change',capture);
  $('new-case').addEventListener('click',function(){var name=$('new-case-name').value.trim();if(!name){status('Name the fictional case first.',true);return;}if(state.cases.length>=30){status('This demonstration supports up to 30 fictional cases.',true);return;}var p={id:AGState.id(),name:name,grade:7,subject:'math',profile:'unknown',labels:[],gifted:false,needs:[]};state.cases.push(AGState.makeCase(p));$('new-case-name').value='';switchCase(p.id);});
  var examples={
    maya:{description:'Fictional case: Maya completes routine mathematics quickly but rarely explains her reasoning in class.',readiness:'Teacher observation: solves extension problems; transfer to unfamiliar tasks still needs assessment.',interests:'Geometry and designing puzzles',learnerVoice:'I want harder problems and time to explain in my own way.',familyVoice:'Reports enthusiasm for puzzles outside school.',barriers:'Routine tasks may offer insufficient challenge; public explanations can feel rushed.',goal:'Explain a mathematical strategy and apply it to a new problem.',baseline:'Independent explanation rubric, 0–4; record task difficulty and scoring criteria.',opportunity:'Advanced geometry inquiry with alternative examples and learner explanation.',support:'Choice of response format and time to prepare an explanation.',resource:'extension'},
    noor:{description:'Fictional case: Noor seeks advanced mathematics but reports discomfort during some school activities.',readiness:'Teacher observation: strong reasoning on selected mathematics tasks; broader readiness remains to be established.',interests:'Patterns and independent investigation',learnerVoice:'I enjoy challenging work and want a quieter way to participate.',familyVoice:'Requests a discussion of school experience and access conditions.',barriers:'Clarify environmental demands and belonging with the learner; this library has no well-being intervention record.',goal:'Participate in a suitably challenging inquiry with accessible conditions.',baseline:'Record opportunity offered, participation, learner feedback, and an independent explanation.',opportunity:'Advanced pattern investigation selected with the learner.',support:'Review environmental access with appropriate school support staff; investigate evidence beyond this library.',resource:'access'},
    sam:{description:'Fictional case: Sam discusses complex ideas but has documented difficulty accessing some written texts.',readiness:'Teacher observation: detailed oral reasoning about themes; assess decoding separately.',interests:'History and evaluating competing explanations',learnerVoice:'I want to discuss difficult ideas without reading speed deciding what I can study.',familyVoice:'Requests access to advanced content alongside targeted skill support.',barriers:'Separate text access, decoding needs, and intellectual challenge.',goal:'Access advanced content while reviewing a confirmed decoding need.',baseline:'Use a suitable decoding measure and a separate content-understanding task; do not combine their scores.',opportunity:'Advanced inquiry using accessible source materials.',support:'Educator-reviewed decoding practice within source scope; accessible content response options.',resource:'access'},
    jordan:{description:'Fictional case: Jordan has documented attendance and progress concerns, with interests that are not fully reflected in current courses.',readiness:'Readiness in areas of interest is unknown; gather work samples and learner input.',interests:'Applied design and practical projects',learnerVoice:'I want a plan that connects schoolwork to something I care about.',familyVoice:'Family account not yet obtained.',barriers:'Clarify scheduling, transport, task access, and reasons for missed participation.',goal:'Improve participation in an agreed learning opportunity and review documented attendance concerns.',baseline:'Attendance, delivery of agreed support, learner account, and separate learning evidence.',opportunity:'Interest-based inquiry, pending readiness and local availability checks.',support:'Review school-participation evidence and program requirements; do not equate a brief check-in with Check & Connect.',resource:'mentor'},
    alex:{description:'Fictional case: Alex succeeds on familiar mathematics tasks and wants to compare different strategies.',readiness:'Teacher observation: reliable routine solutions; flexible transfer to new tasks is unknown.',interests:'Comparing methods and designing examples',learnerVoice:'I want to understand when one strategy is better than another.',familyVoice:'Family account not yet obtained.',barriers:'Task variety and opportunities to discuss strategies need review.',goal:'Compare mathematical strategies and justify a choice on an unfamiliar task.',baseline:'Two comparable strategy tasks scored for explanation; record conditions and uncertainty.',opportunity:'Strategy comparison with a new transfer problem.',support:'Teacher prompts for reflection and accessible explanation.',resource:'extension'}
  };
  $('fill-example').addEventListener('click',function(){var c=current(),example=examples[c.id],p=db.presets.find(function(p){return p.id===c.id;});if(!example||p.grade!==c.context.grade||p.subject!==c.context.subject){status('No authored example fits this custom context. Add fictional information manually.',true);return;}Object.keys(example).forEach(function(k){if(!c.draft[k])c.draft[k]=example[k];});if(c.draft.readinessSource==='unknown')c.draft.readinessSource='observation';if(!c.draft.contextDate)c.draft.contextDate=today();if(!c.draft.responsible)c.draft.responsible='Responsible educator, to confirm';if(!c.draft.delivery)c.draft.delivery='Proposed weekly session; confirm staffing, access, and program-specific requirements.';if(!c.draft.reviewDate){var d=new Date();d.setDate(d.getDate()+14);c.draft.reviewDate=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}bindFields();persist();refresh();document.dispatchEvent(new CustomEvent('achievego:context-change'));status('Authored fictional details added to empty fields. Review the proposed goal, opportunity, support, and feasibility.');});
  $('confirm-plan').addEventListener('click',function(){try{capture();if(current().plans.length>=100)throw new Error('This demo supports up to 100 plan versions per case.');var p=AGState.confirm(current(),db.version);persist();refresh();status('Demo plan '+p.version+' confirmed. Its fields and evidence are retained as a version snapshot.');}catch(e){status(e.message,true);}});
  $('observation-date').value=today();
  $('observation-form').addEventListener('submit',function(event){event.preventDefault();var c=current(),p=c.plans[c.plans.length-1];if(c.observations.length>=500){status('Export this workspace; this demo supports up to 500 observations per case.',true);return;}if(!p){status('Confirm a demo plan before recording observations.',true);return;}var value=$('observation-value').value;var o={id:AGState.id(),planId:p.id,date:$('observation-date').value,measure:$('observation-measure').value.trim(),value:value===''?null:Number(value),unit:$('observation-unit').value.trim(),ai:$('observation-ai').value,accommodations:$('observation-accommodations').value,delivery:$('observation-delivery').value,feedback:$('observation-feedback').value,synthetic:true};var proposed=AGState.clone(state);AGState.current(proposed).observations.push(o);try{state=AGState.validate(proposed,db);persist();refresh();status('Synthetic observation recorded. Missing values remain missing.');}catch(e){status(e.message,true);}});
  $('load-observations').addEventListener('click',function(){var c=current(),p=c.plans[c.plans.length-1];if(!p){status('Confirm a demo plan before loading follow-up observations.',true);return;}if(c.observations.some(function(o){return o.planId===p.id&&o.measure==='Explanation rubric (authored example)';})){status('This plan already has the authored example. Add a separate observation if needed.');return;}[[-14,1,'none'],[-7,3,'hints'],[0,2,'none']].forEach(function(row){var d=new Date();d.setDate(d.getDate()+row[0]);var date=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');c.observations.push({id:AGState.id(),planId:p.id,date:date,measure:'Explanation rubric (authored example)',value:row[1],unit:'points, 0–4',ai:row[2],accommodations:p.fields.accommodations,delivery:'Fictional session completed; task difficulty and scoring need review.',feedback:row[2]==='hints'?'The hint helped me get started.':'I explained my own approach.',synthetic:true});});persist();refresh();status('Three authored synthetic observations loaded. Assisted and independent conditions are shown separately.');});
  $('review-form').addEventListener('submit',function(event){event.preventDefault();var c=current(),p=c.plans[c.plans.length-1],rationale=$('review-rationale').value.trim();if(!p||!rationale){status('Confirm a plan and provide the review rationale first.',true);return;}if(c.reviews.length>=100){status('This demo supports up to 100 reviews per case.',true);return;}c.reviews.push({id:AGState.id(),planId:p.id,date:today(),decision:$('review-decision').value,rationale:rationale,nextPlanId:null,synthetic:true});$('review-rationale').value='';persist();refresh();status('Demo review recorded. For an adaptation or replacement, revise the draft and confirm its next version.');});
  $('workspace-export').addEventListener('click',function(){capture();download(state,'AchieveGo-fictional-workspace.json');status('Workspace exported with plan versions, evidence IDs, synthetic observations, and reviews.');});
  $('workspace-import').addEventListener('click',function(){$('import-file').click();});
  $('import-file').addEventListener('change',async function(){var f=this.files[0];pendingImport=null;$('import-preview').hidden=true;if(!f)return;try{if(f.size>2000000)throw new Error('Choose a JSON workspace under 2 MB.');pendingImport=AGState.parse(await f.text(),db);$('import-summary').textContent='Validated fictional workspace: '+pendingImport.cases.length+' cases, '+pendingImport.cases.reduce(function(n,c){return n+c.plans.length;},0)+' plan versions. Confirming replaces this browser’s current demo. Export current work first if needed.';$('import-preview').hidden=false;status('Import validated. Review the replacement before confirming.');}catch(e){status('Import rejected: '+e.message,true);}this.value='';});
  $('import-cancel').addEventListener('click',function(){pendingImport=null;$('import-preview').hidden=true;status('Import cancelled.');});
  $('import-confirm').addEventListener('click',function(){if(!pendingImport)return;state=pendingImport;pendingImport=null;blocked=false;$('import-preview').hidden=true;syncOptions();switchCase(state.activeCaseId);status('Validated fictional workspace imported.');});
  function syncOptions(){var select=$('preset');select.replaceChildren();state.cases.forEach(function(c){var o=document.createElement('option');o.value=c.id;o.textContent=c.name;select.appendChild(o);});}
  $('workspace-reset').addEventListener('click',function(){if(!window.confirm('Reset all fictional cases, plans, observations, and reviews saved in this browser? Export first to keep a copy.'))return;try{storage.removeItem(AGState.KEY);}catch(e){}state=AGState.fresh(db);blocked=false;compared.clear();syncOptions();switchCase(state.activeCaseId);status('Fictional workspace reset.');});
  $('print-plan').addEventListener('click',function(){document.body.classList.add('printing-plan');window.print();});window.addEventListener('afterprint',function(){document.body.classList.remove('printing-plan');});
  var comparison=document.createElement('section');comparison.className='card comparison-panel';comparison.id='evidence-comparison';comparison.hidden=true;$('library-view').insertBefore(comparison,$('all-cards'));
  function compare(){comparison.hidden=!compared.size;comparison.innerHTML='<h3>Compare evidence scope</h3><p>Ratings retain their original frameworks. They do not rank individual benefit.</p><div class="comparison-grid">'+Array.from(compared).map(function(id){var r=db.evidence_records.find(function(r){return r.id===id;});return '<article><h4>'+esc(r.title)+'</h4>'+entries({outcome:r.outcome,population:r.population,evidenceFramework:r.rating_framework,rating:r.rating,implementation:r.implementation,limitations:r.limitations})+'<button data-remove-compare="'+esc(id)+'">Remove</button></article>';}).join('')+'</div>';}
  document.addEventListener('click',function(event){var add=event.target.closest('[data-compare]'),remove=event.target.closest('[data-remove-compare]');if(add){if(compared.size>=3&&!compared.has(add.dataset.compare)){status('Compare up to three evidence records at a time.',true);comparison.scrollIntoView({block:'start'});return;}compared.add(add.dataset.compare);compare();comparison.scrollIntoView({block:'start'});}if(remove){compared.delete(remove.dataset.removeCompare);compare();}});
  window.AGFlow={refresh:refresh,state:function(){return AGState.clone(state);},planExport:function(){return AGState.clone(current());},assistantContext:function(){var c=current();return {stage:window.AGWorkspace.stage(),learning_goal:c.draft.goal,readiness:c.draft.readiness,readiness_source:c.draft.readinessSource,learner_account:c.draft.learnerVoice,access_barriers:c.draft.barriers};}};
  syncOptions();switchCase(state.activeCaseId);$('save-status').textContent=blocked?loaded.message:$('save-status').textContent;
}());
